import XCTest
@testable import tinys3

// swiftlint:disable line_length
final class UploadPartRequestTests: XCTestCase, RequestTest {

    var request: AWSRequest = {
        let part = MultipartUploadOperation.AWSPartData(
            uploadId: testUploadId,
            number: 42,
            data: Data("test$content\nwith multiple lines!".utf8)
        )
        return AWSRequest.uploadPartRequest(
            bucket: testBucketName,
            key: testObjectKey,
            part: part,
            credentials: .testDefault,
            date: .testDefault
        )
    }()

    func testThatCanonicalUriIsCorrect() throws {
        XCTAssertEqual(testObjectKey, request.canonicalUri)
    }

    func testThatCanonicalQueryStringIsCorrect() throws {
        XCTAssertEqual("partNumber=42&uploadId=\(testUploadId)", request.canonicalQueryString)
    }

    // Use `self.request.printDebugSigningRubyCode()` to compare the expected values with the ones generated by the AWS Ruby gem
    func testThatCanonicalHeaderStringIsCorrect() throws {
        XCTAssertEqual("""
            host:my-test-bucket.s3.amazonaws.com
            x-amz-content-sha256:09ca2f2ca4a09d67c7c2c55a1135635437b32d59cc71eaa0746254c174795ab3
            x-amz-date:20130524T000000Z
            """, request.canonicalHeaderString)
    }

    func testThatSignedHeaderStringIsCorrect() throws {
        XCTAssertEqual("host;x-amz-content-sha256;x-amz-date", request.signedHeaderString)
    }

    // Use `self.request.printDebugSigningRubyCode()` to compare the expected values with the ones generated by the AWS Ruby gem
    func testThatCanonicalRequestIsValid() throws {
        XCTAssertEqual("""
            PUT
            /my/path/to/stuff.txt
            partNumber=42&uploadId=q4sTIuOL6NEI9mEHjfORyTfaMSvkA3ebJhiwuTi4xfPhqtM8yasXIjBM8tuGhq9TpdfrNi7uhdHBWWeadoRo3iJ770lPeC8Px1w0stBEXMAZN2jZYrJDqSAWR3DkUJj9
            host:my-test-bucket.s3.amazonaws.com
            x-amz-content-sha256:09ca2f2ca4a09d67c7c2c55a1135635437b32d59cc71eaa0746254c174795ab3
            x-amz-date:20130524T000000Z

            host;x-amz-content-sha256;x-amz-date
            09ca2f2ca4a09d67c7c2c55a1135635437b32d59cc71eaa0746254c174795ab3
            """, request.canonicalRequest)
    }

    // Use `self.request.printDebugSigningRubyCode()` to compare the expected values with the ones generated by the AWS Ruby gem
    func testThatStringToSignIsValid() throws {
        XCTAssertEqual("""
            AWS4-HMAC-SHA256
            20130524T000000Z
            20130524/us-east-1/s3/aws4_request
            c25bb5bdbbb4701c6bbfd80f1904594d949dab49d4abb7755f3c9116fe637f4d
            """, request.stringToSign)
    }

    func testThatSignatureIsValid() throws {
        XCTAssertEqual("505e884ec3b6111995f62700860a5f16cc6b1115b57b45c77bd749083927a66a", request.signature)
    }

    // Use `self.request.printDebugSigningRubyCode()` to compare the expected values with the ones generated by the AWS Ruby gem
    func testThatAuthorizationHeaderValueIsCorrect() throws {
        XCTAssertEqual("""
            AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20130524/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=505e884ec3b6111995f62700860a5f16cc6b1115b57b45c77bd749083927a66a
            """, request.authorizationHeaderValue)
    }
}
// swiftlint:enable line_length
