# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buildkite-agent pipeline upload`

agents:
  queue: mac

env:
  IMAGE_ID: xcode-26.1.1

# This is the default pipeline – it will build and test the app
steps:
  #################
  # Build and Test
  #################
  - label: "🧪 Build and Test"
    key: "test"
    command: |
      echo "--- :swift: Building + Testing"
      install_swiftpm_dependencies
      swift test
    plugins: [$CI_TOOLKIT_PLUGIN]

  #################
  # Lint
  #################
  - label: "🧪 Lint Swift"
    command: swiftlint
    agents:
      queue: "linter"

  - label: "🧪 Lint Ruby"
    command: rubocop
    agents:
      queue: "linter"

  #################
  # Validate Release Build
  #################
  - label: "🧪 Validate Release Build"
    key: "validate-release-build"
    command: |
      install_gems
      bundle exec fastlane set_up_signing
      make build verify-signing
    plugins: [$CI_TOOLKIT_PLUGIN]

  #################
  # Publish the Binary (if we're building a tag)
  #################
  - label: "⬆️ Publish Binary"
    key: "publish"
    command: |
      install_gems
      bundle exec fastlane set_up_signing
      make build
      bundle exec fastlane upload_release
    plugins: [$CI_TOOLKIT_PLUGIN]
    depends_on:
      - "test"
      - "validate-release-build"
    if: build.tag != null
