# frozen_string_literal: true

fastlane_require 'digest'
fastlane_require 'zip'

UI.user_error!('Please run fastlane via `bundle exec`') unless FastlaneCore::Helper.bundler?

########################################################################
# Constants and Environment Variables
########################################################################
PROJECT_ROOT_FOLDER = File.dirname(File.expand_path(__dir__))
SECRETS_FOLDER = File.join(PROJECT_ROOT_FOLDER, '.secrets')

ARTIFACTS_ROOT = File.join(PROJECT_ROOT_FOLDER, '.build', 'artifacts', 'release')
ARTIFACT_PATHS = Dir.glob(File.join(ARTIFACTS_ROOT, '*'))
ZIP_FILE_PATH = File.join(PROJECT_ROOT_FOLDER, '.build', 'artifacts', 'hostmgr.zip')
GITHUB_REPO = 'automattic/hostmgr'

APPLE_TEAM_ID = 'PZYM8XX95Q'
APPLE_BUNDLE_IDENTIFIER = 'com.automattic.hostmgr'

ASC_API_KEY_ENV_VARS = %w[
  APP_STORE_CONNECT_API_KEY_KEY_ID
  APP_STORE_CONNECT_API_KEY_ISSUER_ID
  APP_STORE_CONNECT_API_KEY_KEY
].freeze

CODE_SIGNING_STORAGE_ENV_VARS = %w[
  MATCH_S3_ACCESS_KEY
  MATCH_S3_SECRET_ACCESS_KEY
].freeze

before_all do
  setup_ci # Fixes weird Keychain bugs
end

desc 'Upload the Release Build products to Github under a new release'
lane :upload_release do
  UI.user_error!('No build products are present – did you run `make build-release`?') if ARTIFACT_PATHS.empty?

  create_release_zip

  tag = ENV['BUILDKITE_TAG'] ||= prompt(text: "Enter the tag name you'd like to use")

  set_github_release(
    repository_name: GITHUB_REPO,
    api_token: ENV.fetch('GITHUB_TOKEN', nil),
    name: tag,
    tag_name: tag,
    description: Digest::SHA256.file(ZIP_FILE_PATH).to_s,
    upload_assets: [ZIP_FILE_PATH] + ARTIFACT_PATHS,
    is_prerelease: false
  )
end

desc 'Download all certificates and provisioning profiles for code signing'
lane :set_up_signing do |readonly: true|
  set_up_signing_development(readonly: readonly)
  set_up_signing_release(readonly: readonly)
end

desc 'Download the development signing certificates to this machine'
lane :set_up_signing_development do |readonly: true|
  set_up_certificate_in_keychain(type: 'development', readonly: readonly)
end

desc 'Download the release signing certificates to this machine'
lane :set_up_signing_release do |readonly: true|
  set_up_certificate_in_keychain(type: 'appstore', readonly: readonly)
end

def create_release_zip
  File.delete(ZIP_FILE_PATH) if File.file? ZIP_FILE_PATH

  Dir.chdir(ARTIFACTS_ROOT) do
    Zip::File.open(ZIP_FILE_PATH, Zip::File::CREATE) do |zipfile|
      %w[hostmgr hostmgr-helper].each do |f|
        zipfile.add(File.basename(f), File.join(ARTIFACTS_ROOT, f))
      end
    end
  end
end

# Use this to ensure all env vars a lane requires are set.
#
# The best place to call this is at the start of a lane, to fail early.
def require_env_vars!(*keys)
  keys.each { |key| get_required_env!(key) }
end

# Use this instead of getting values from `ENV` directly. It will throw an error if the requested value is missing.
def get_required_env!(key)
  return ENV.fetch(key) if ENV.key?(key)

  UI.user_error!("Environment variable `#{key}` is not set.")
end

def set_up_certificate_in_keychain(type:, readonly:)
  require_env_vars!(*ASC_API_KEY_ENV_VARS, *CODE_SIGNING_STORAGE_ENV_VARS)

  # This will fetch the certificate and provisioning profile for the given type from remote storage.
  # It will then set them up in the local keychain, where 'codesign' looks for identities.
  #
  # Notice we do not need the provisioning profile because we sign with 'codesign' elsewhere.
  # However, there is no other way to set up the certificate in the keychain.
  # Fastlane offers a tool called cert, but it only downloads certificates.
  sync_code_signing(
    platform: 'macos',
    app_identifier: APPLE_BUNDLE_IDENTIFIER,
    team_id: APPLE_TEAM_ID,
    api_key: app_store_connect_api_key,
    type: type,
    storage_mode: 's3',
    s3_region: 'us-east-2',
    s3_bucket: 'a8c-fastlane-match',
    readonly: readonly
  )
end
